export const FETCH_VALIDATORS_FAILED = "FETCH_VALIDATORS_FAILED";
export const SET_VALIDATORS = "SET_VALIDATORS";
export const FILTER_VALIDATORS = "FILTER_VALIDATORS";

export const FETCH_REFERRERS = "FETCH_REFERRERS";
export const FETCH_REFERRERS_FAILED = "FETCH_REFERRERS_FAILED";
export const SET_REFERRERS = "SET_REFERRERS";
